version: 0.2

phases:
  install:
    commands:
      - pip install troposphere awacs

  build: 
    commands:
      - python codebuild/sam/template.py > codebuild/sam/template.json

artifacts: 
  files:
    - codebuild/sam/template.json
